
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("6004d9b2-42ae-41a5-89fb-e0f881f6ab33")>

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class LocalDatabaseEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new LocalDatabaseEntities object using the connection string found in the 'LocalDatabaseEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=LocalDatabaseEntities", "LocalDatabaseEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new LocalDatabaseEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "LocalDatabaseEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new LocalDatabaseEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "LocalDatabaseEntities")
    MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Logs() As ObjectSet(Of Log)
        Get
            If (_Logs Is Nothing) Then
                _Logs = MyBase.CreateObjectSet(Of Log)("Logs")
            End If
            Return _Logs
        End Get
    End Property

    Private _Logs As ObjectSet(Of Log)

    #End Region
    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Logs EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLogs(ByVal log As Log)
        MyBase.AddObject("Logs", log)
    End Sub

    #End Region
End Class

#End Region
#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="LocalDatabaseModel", Name:="Log")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Log
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Log object.
    ''' </summary>
    ''' <param name="event">Initial value of the Event property.</param>
    ''' <param name="createdAt">Initial value of the CreatedAt property.</param>
    Public Shared Function CreateLog([event] As Global.System.String, createdAt As Global.System.DateTime) As Log
        Dim log as Log = New Log
        log.[Event] = [event]
        log.CreatedAt = createdAt
        Return log
    End Function

    #End Region
    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property [Event]() As Global.System.String
        Get
            Return _Event
        End Get
        Set
            If (_Event <> Value) Then
                OnEventChanging(value)
                ReportPropertyChanging("Event")
                _Event = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Event")
                OnEventChanged()
            End If
        End Set
    End Property

    Private _Event As Global.System.String
    Private Partial Sub OnEventChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnEventChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Status() As Global.System.String
        Get
            Return _Status
        End Get
        Set
            OnStatusChanging(value)
            ReportPropertyChanging("Status")
            _Status = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Status")
            OnStatusChanged()
        End Set
    End Property

    Private _Status As Global.System.String
    Private Partial Sub OnStatusChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnStatusChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Message() As Global.System.String
        Get
            Return _Message
        End Get
        Set
            OnMessageChanging(value)
            ReportPropertyChanging("Message")
            _Message = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Message")
            OnMessageChanged()
        End Set
    End Property

    Private _Message As Global.System.String
    Private Partial Sub OnMessageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnMessageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property User() As Global.System.String
        Get
            Return _User
        End Get
        Set
            OnUserChanging(value)
            ReportPropertyChanging("User")
            _User = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("User")
            OnUserChanged()
        End Set
    End Property

    Private _User As Global.System.String
    Private Partial Sub OnUserChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUserChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CreatedAt() As Global.System.DateTime
        Get
            Return _CreatedAt
        End Get
        Set
            If (_CreatedAt <> Value) Then
                OnCreatedAtChanging(value)
                ReportPropertyChanging("CreatedAt")
                _CreatedAt = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("CreatedAt")
                OnCreatedAtChanged()
            End If
        End Set
    End Property

    Private _CreatedAt As Global.System.DateTime
    Private Partial Sub OnCreatedAtChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnCreatedAtChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ExtraInformation() As Global.System.String
        Get
            Return _ExtraInformation
        End Get
        Set
            OnExtraInformationChanging(value)
            ReportPropertyChanging("ExtraInformation")
            _ExtraInformation = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("ExtraInformation")
            OnExtraInformationChanged()
        End Set
    End Property

    Private _ExtraInformation As Global.System.String
    Private Partial Sub OnExtraInformationChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnExtraInformationChanged()
    End Sub

    #End Region
End Class

#End Region

