default: 
  RetryMilliseconds: 500
  RetryCount: 3
  LoginName: AsiAR
  fromName: Webmaster
  FrontImageMaxSize: 200000
  toEmail: wphaskett@advantos.net
  specialServices: http://localhost/sps/default.aspx?mwCustNo=0&amp;dwAcctLogin=login
  DemoMgmtCo: pmsi
  DemoHoa: pmsi/lakeway
  ExEmailTo: Hometast3Errors@hometastic.com
  SessionTimeout: 20
  WhiteListDocumentUpload: jpeg,jpg,gif,png,doc,docx,xls,xlsx,pdf
  WhiteListEmailAttachment: txt,zip,tar,jpeg,jpg,gif,png,pdf

WIN07:
  Hometast3Info: C:\src\hometastic\Hometast3Info
  toEmail: gmhawash@gmail.com
  specialServices: http://localhost/sps/default.aspx?mwCustNo=0&amp;dwAcctLogin=login